### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Mst8827** [Mst8827/chat-space#9]
#IPアドレス
18.178.91.67

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by Mst8827** [comment]
> ご提出ありがとうございます！
> 確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
> おめでとうございます！
